name: profinix_app
description: "Sri RK Woodlands"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore:
  json_annotation:
  responsive_builder: ^0.7.0
  device_preview: 
  get: 
  http: 
  translator: 
  flutter_dotenv: 
  flutter_form_builder:
  form_builder_validators:
  intl: 
  logger:
  mocktail: 
  syncfusion_flutter_charts: 
  table_calendar: 
  

  firebase_core: ^3.11.0 
  firebase_auth: ^5.4.2 
  in_app_review: ^2.0.9
  flutter_card_swiper: ^7.0.1
  infinite_scroll_pagination: ^4.0.0
  pdf: ^3.10.8
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.0.0
  intl_phone_number_input: ^0.7.4
  video_player: ^2.9.2
  flutter_neumorphic: ^3.2.0
  carousel_slider: ^5.0.0
  visibility_detector: ^0.4.0+2
  animated_text_kit: ^4.2.2
 
  razorpay_flutter: ^1.3.4
  google_sign_in: ^6.2.2
  cached_network_image: ^3.4.1

  
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
  build_runner:
  json_serializable: 

flutter:
  uses-material-design: true
  assets:
    #- .enV
    #- assets/google_logo.png
    #- assets/facebook_logo.png
    
    - assets/
    - assets/images/
    - assets/background/
    - assets/logo/
    - assets/features/
    - assets/products/
   



fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
      
    